In [54]:
import pandas as pd
df=pd.read_csv("StudentsPerformance.csv")
print(df)

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score   age
0                      none          72             72             74  56.0
1                 completed          69             90             88  67.0
2                      none          90             95             93  88.0
3                      none          47             57             44  93.0
4                      none          76             78             75  44.0
..                      ...         ...            ...            ...   ...
995               completed          88             99             95   NaN
996                    none          62             55             55   NaN
997               completed          59             71             65   NaN
998               completed          68             78             77   NaN
999                    none          77             86             86   NaN

[1000 rows x 9 columns]

In [2]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,age
0,female,group B,bachelor's degree,standard,none,72,72,74,56.0
1,female,group C,some college,standard,completed,69,90,88,67.0
2,female,group B,master's degree,standard,none,90,95,93,88.0
3,male,group A,associate's degree,free/reduced,none,47,57,44,93.0
4,male,group C,some college,standard,none,76,78,75,44.0

In [3]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,age
995,female,group E,master's degree,standard,completed,88,99,95,NaN
996,male,group C,high school,free/reduced,none,62,55,55,NaN
997,female,group C,high school,free/reduced,completed,59,71,65,NaN
998,female,group D,some college,standard,completed,68,78,77,NaN
999,female,group D,some college,free/reduced,none,77,86,86,NaN

In [5]:
df.shape

(1000, 9)

In [6]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'age'],
      dtype='str')

In [7]:
df.dtypes

gender                             str
race/ethnicity                     str
parental level of education        str
lunch                              str
test preparation course            str
math score                       int64
reading score                    int64
writing score                    int64
age                            float64
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
 8   age                          98 non-null     float64
dtypes: float64(1), int64(3), str(5)
memory usage: 50.9 KB

In [9]:
df.describe()

       math score  reading score  writing score        age
count  1000.00000    1000.000000    1000.000000  98.000000
mean     66.08900      69.169000      68.054000  66.642857
std      15.16308      14.600192      15.195657  13.372730
min       0.00000      17.000000      10.000000  28.000000
25%      57.00000      59.000000      57.750000  57.000000
50%      66.00000      70.000000      69.000000  66.000000
75%      77.00000      79.000000      79.000000  76.000000
max     100.00000     100.000000     100.000000  93.000000

In [10]:
df["age"].mean()

np.float64(66.64285714285714)

In [11]:
df["age"].median()

np.float64(66.0)

In [12]:
df["age"].mode()

0    65.0
Name: age, dtype: float64

In [13]:
df["age"].var()

np.float64(178.8298969072165)

In [14]:
df["age"].std()

np.float64(13.37272959822401)

In [15]:
df["age"].min()

np.float64(28.0)

In [16]:
df["age"].max()

np.float64(93.0)

In [17]:
df["age"].count()

np.int64(98)

In [23]:
df["race/ethnicity"].unique()

<StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str

In [25]:
df["race/ethnicity"].nunique()

5

In [26]:
df["race/ethnicity"].value_counts()

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

In [27]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,age
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,True
996,False,False,False,False,False,False,False,False,True
997,False,False,False,False,False,False,False,False,True
998,False,False,False,False,False,False,False,False,True
999,False,False,False,False,False,False,False,False,True

In [28]:
df.isnull().sum()

gender                           0
race/ethnicity                   0
parental level of education      0
lunch                            0
test preparation course          0
math score                       0
reading score                    0
writing score                    0
age                            902
dtype: int64

In [30]:
df.isnull().mean()*100

gender                          0.0
race/ethnicity                  0.0
parental level of education     0.0
lunch                           0.0
test preparation course         0.0
math score                      0.0
reading score                   0.0
writing score                   0.0
age                            90.2
dtype: float64

In [31]:
df.dropna()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,age
0,female,group B,bachelor's degree,standard,none,72,72,74,56.0
1,female,group C,some college,standard,completed,69,90,88,67.0
2,female,group B,master's degree,standard,none,90,95,93,88.0
3,male,group A,associate's degree,free/reduced,none,47,57,44,93.0
4,male,group C,some college,standard,none,76,78,75,44.0
...,...,...,...,...,...,...,...,...,...
93,male,group C,associate's degree,free/reduced,completed,43,45,50,57.0
94,female,group B,some college,standard,none,79,86,92,62.0
95,male,group C,associate's degree,free/reduced,completed,78,81,82,76.0
96,male,group B,some high school,standard,completed,65,66,62,76.0
97,female,group E,some college,standard,completed,63,72,70,82.0

In [32]:
df.fillna(0)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,age
0,female,group B,bachelor's degree,standard,none,72,72,74,56.0
1,female,group C,some college,standard,completed,69,90,88,67.0
2,female,group B,master's degree,standard,none,90,95,93,88.0
3,male,group A,associate's degree,free/reduced,none,47,57,44,93.0
4,male,group C,some college,standard,none,76,78,75,44.0
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,0.0
996,male,group C,high school,free/reduced,none,62,55,55,0.0
997,female,group C,high school,free/reduced,completed,59,71,65,0.0
998,female,group D,some college,standard,completed,68,78,77,0.0
999,female,group D,some college,free/reduced,none,77,86,86,0.0

In [33]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.drop_duplicates()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,age
0,female,group B,bachelor's degree,standard,none,72,72,74,56.0
1,female,group C,some college,standard,completed,69,90,88,67.0
2,female,group B,master's degree,standard,none,90,95,93,88.0
3,male,group A,associate's degree,free/reduced,none,47,57,44,93.0
4,male,group C,some college,standard,none,76,78,75,44.0
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,NaN
996,male,group C,high school,free/reduced,none,62,55,55,NaN
997,female,group C,high school,free/reduced,completed,59,71,65,NaN
998,female,group D,some college,standard,completed,68,78,77,NaN
999,female,group D,some college,free/reduced,none,77,86,86,NaN

In [36]:
df["age"]

0      56.0
1      67.0
2      88.0
3      93.0
4      44.0
       ...
995     NaN
996     NaN
997     NaN
998     NaN
999     NaN
Name: age, Length: 1000, dtype: float64

In [37]:
df[["age","gender"]]

      age  gender
0    56.0  female
1    67.0  female
2    88.0  female
3    93.0    male
4    44.0    male
..    ...     ...
995   NaN  female
996   NaN    male
997   NaN  female
998   NaN  female
999   NaN  female

[1000 rows x 2 columns]

In [38]:
df.iloc[0:5]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,age
0,female,group B,bachelor's degree,standard,none,72,72,74,56.0
1,female,group C,some college,standard,completed,69,90,88,67.0
2,female,group B,master's degree,standard,none,90,95,93,88.0
3,male,group A,associate's degree,free/reduced,none,47,57,44,93.0
4,male,group C,some college,standard,none,76,78,75,44.0

In [39]:
df[df["age"]>30]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,age
0,female,group B,bachelor's degree,standard,none,72,72,74,56.0
1,female,group C,some college,standard,completed,69,90,88,67.0
2,female,group B,master's degree,standard,none,90,95,93,88.0
3,male,group A,associate's degree,free/reduced,none,47,57,44,93.0
4,male,group C,some college,standard,none,76,78,75,44.0
...,...,...,...,...,...,...,...,...,...
93,male,group C,associate's degree,free/reduced,completed,43,45,50,57.0
94,female,group B,some college,standard,none,79,86,92,62.0
95,male,group C,associate's degree,free/reduced,completed,78,81,82,76.0
96,male,group B,some high school,standard,completed,65,66,62,76.0
97,female,group E,some college,standard,completed,63,72,70,82.0

In [40]:
df.rename(columns={"age":"age_years"})

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,age_years
0,female,group B,bachelor's degree,standard,none,72,72,74,56.0
1,female,group C,some college,standard,completed,69,90,88,67.0
2,female,group B,master's degree,standard,none,90,95,93,88.0
3,male,group A,associate's degree,free/reduced,none,47,57,44,93.0
4,male,group C,some college,standard,none,76,78,75,44.0
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,NaN
996,male,group C,high school,free/reduced,none,62,55,55,NaN
997,female,group C,high school,free/reduced,completed,59,71,65,NaN
998,female,group D,some college,standard,completed,68,78,77,NaN
999,female,group D,some college,free/reduced,none,77,86,86,NaN

In [44]:
df.drop("age",axis=1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,7.2,74
1,female,group C,some college,standard,completed,69,6.9,88
2,female,group B,master's degree,standard,none,90,9.0,93
3,male,group A,associate's degree,free/reduced,none,47,4.7,44
4,male,group C,some college,standard,none,76,7.6,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,8.8,95
996,male,group C,high school,free/reduced,none,62,6.2,55
997,female,group C,high school,free/reduced,completed,59,5.9,65
998,female,group D,some college,standard,completed,68,6.8,77
999,female,group D,some college,free/reduced,none,77,7.7,86

In [48]:
pd.concat([df,df])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,age
0,female,group B,bachelor's degree,standard,none,72,7.2,74,56.0
1,female,group C,some college,standard,completed,69,6.9,88,67.0
2,female,group B,master's degree,standard,none,90,9.0,93,88.0
3,male,group A,associate's degree,free/reduced,none,47,4.7,44,93.0
4,male,group C,some college,standard,none,76,7.6,75,44.0
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,8.8,95,NaN
996,male,group C,high school,free/reduced,none,62,6.2,55,NaN
997,female,group C,high school,free/reduced,completed,59,5.9,65,NaN
998,female,group D,some college,standard,completed,68,6.8,77,NaN
999,female,group D,some college,free/reduced,none,77,7.7,86,NaN