In [2]:
# Import pandas library
import pandas as pd

In [3]:

# Create a library dataset with missing values
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL', 'Python', 'Java'],
    'Price': [400, 500, None, 350, 400, None],
    'Rating': [4, 5, 3, None, 4, 5],
    'Category': ['Programming', 'Programming', None, 'Database', 'Programming', 'Programming'],
    'Publisher': ['ABC', 'XYZ', 'ABC', None, 'ABC', 'XYZ']
}

# Convert dictionary into a DataFrame
df = pd.DataFrame(data)

# Display the dataset
print(df)

            Book  Price  Rating     Category Publisher
0         Python  400.0     4.0  Programming       ABC
1           Java  500.0     5.0  Programming       XYZ
2  C Programming    NaN     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC
5           Java    NaN     5.0  Programming       XYZ

In [4]:
# Display the first five rows
df.head()

            Book  Price  Rating     Category Publisher
0         Python  400.0     4.0  Programming       ABC
1           Java  500.0     5.0  Programming       XYZ
2  C Programming    NaN     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC

In [5]:

# Display the last five rows
df.tail()

            Book  Price  Rating     Category Publisher
1           Java  500.0     5.0  Programming       XYZ
2  C Programming    NaN     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC
5           Java    NaN     5.0  Programming       XYZ

In [6]:
# Display the number of rows and columns
df.shape

(6, 5)

In [7]:

# Display all column names
df.columns

Index(['Book', 'Price', 'Rating', 'Category', 'Publisher'], dtype='str')

In [8]:
# Display the data type of each column
df.dtypes

Book             str
Price        float64
Rating       float64
Category         str
Publisher        str
dtype: object

In [9]:
# Display dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Book       6 non-null      str
 1   Price      4 non-null      float64
 2   Rating     5 non-null      float64
 3   Category   5 non-null      str
 4   Publisher  5 non-null      str
dtypes: float64(2), str(3)
memory usage: 240.0 bytes

In [10]:
# Identify missing values in each cell
print(df.isnull())

    Book  Price  Rating  Category  Publisher
0  False  False   False     False      False
1  False  False   False     False      False
2  False   True   False      True      False
3  False  False    True     False       True
4  False  False   False     False      False
5  False   True   False     False      False

In [11]:

# Count missing values in each column
print(df.isnull().sum())

Book         0
Price        2
Rating       1
Category     1
Publisher    1
dtype: int64

In [12]:

# Fill missing Price values with the mean price
df['Price'] = df['Price'].fillna(df['Price'].mean())

# Display the updated dataset
print(df)

            Book  Price  Rating     Category Publisher
0         Python  400.0     4.0  Programming       ABC
1           Java  500.0     5.0  Programming       XYZ
2  C Programming  412.5     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC
5           Java  412.5     5.0  Programming       XYZ

In [13]:

# Calculate the mean book price
print("Mean Price:", df['Price'].mean())

Mean Price: 412.5

In [14]:

# Calculate the most frequently occurring book price
print("Mode Price:", df['Price'].mode().tolist())

Mode Price: [400.0, 412.5]

In [15]:
# Calculate the most frequently occurring book rating
print("Mode Rating:", df['Rating'].mode().tolist())

Mode Rating: [4.0, 5.0]

In [16]:
# Calculate the most frequently occurring book category
print("Mode Category:", df['Category'].mode().tolist())

Mode Category: ['Programming']

In [19]:

# Recreate the original library dataset
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL', 'Python', 'Java'],
    'Price': [400, 500, None, 350, 400, None],
    'Rating': [4, 5, 3, None, 4, 5],
    'Category': ['Programming', 'Programming', None, 'Database', 'Programming', 'Programming'],
    'Publisher': ['ABC', 'XYZ', 'ABC', None, 'ABC', 'XYZ']
}

# Convert dictionary into a DataFrame
df = pd.DataFrame(data)

In [18]:
# Fill missing Price values with the median price
df['Price'] = df['Price'].fillna(df['Price'].median())

# Display the updated dataset
print(df)

            Book  Price  Rating     Category Publisher
0         Python  400.0     4.0  Programming       ABC
1           Java  500.0     5.0  Programming       XYZ
2  C Programming  400.0     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC
5           Java  400.0     5.0  Programming       XYZ

In [20]:

# Create library data with missing categories
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL', 'HTML'],
    'Category': ['Programming', 'Programming', None, 'Database', None]
}

# Convert dictionary into a DataFrame
df = pd.DataFrame(data)

In [21]:
# Display data before forward fill
print("Before Forward Fill:")
print(df)

Before Forward Fill:
            Book     Category
0         Python  Programming
1           Java  Programming
2  C Programming          NaN
3            SQL     Database
4           HTML          NaN

In [22]:
# Fill missing categories with the previous available category
df['Category'] = df['Category'].ffill()

# Display data after forward fill
print("\nAfter Forward Fill:")
print(df)

After Forward Fill:
            Book     Category
0         Python  Programming
1           Java  Programming
2  C Programming  Programming
3            SQL     Database
4           HTML     Database

In [25]:

# Import LabelEncoder for categorical encoding
from sklearn.preprocessing import LabelEncoder

In [26]:

# Create library category data
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL'],
    'Category': ['Programming', 'Programming', 'Programming', 'Database']
}

# Convert dictionary into a DataFrame
df = pd.DataFrame(data)

# Display the dataset
print(df)

            Book     Category
0         Python  Programming
1           Java  Programming
2  C Programming  Programming
3            SQL     Database

In [27]:
# Create a LabelEncoder object
encoder = LabelEncoder()

# Convert categories into numerical labels
df['Category_Encoded'] = encoder.fit_transform(df['Category'])

# Display the encoded dataset
print(df)

            Book     Category  Category_Encoded
0         Python  Programming                 1
1           Java  Programming                 1
2  C Programming  Programming                 1
3            SQL     Database                 0

In [28]:

# Display the category names used by the encoder
print(encoder.classes_)

['Database' 'Programming']

In [29]:
# Import pandas library
import pandas as pd

# Create library category data
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL'],
    'Category': ['Programming', 'Programming', 'Programming', 'Database']
}

# Convert dictionary into a DataFrame
df = pd.DataFrame(data)

# Display the dataset
print(df)

            Book     Category
0         Python  Programming
1           Java  Programming
2  C Programming  Programming
3            SQL     Database

In [30]:
# Create separate columns for each category
encoded_df = pd.get_dummies(df, columns=['Category'])

# Display the encoded dataset
print(encoded_df)

            Book  Category_Database  Category_Programming
0         Python              False                  True
1           Java              False                  True
2  C Programming              False                  True
3            SQL               True                 False

In [31]:
# Convert categories into integer columns containing 0 and 1
encoded_df = pd.get_dummies(
    df,
    columns=['Category'],
    dtype=int
)

# Display the encoded dataset
print(encoded_df)

            Book  Category_Database  Category_Programming
0         Python                  0                     1
1           Java                  0                     1
2  C Programming                  0                     1
3            SQL                  1                     0

In [32]:

# Count the total number of missing values in the dataset
print("Total Missing Values:", df.isnull().sum().sum())

Total Missing Values: 0

In [33]:

# Display rows that contain at least one missing value
print(df[df.isnull().any(axis=1)])

Empty DataFrame
Columns: [Book, Category]
Index: []

In [34]:
# Import pandas
import pandas as pd

# Create library dataset with missing values
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL', 'Python', 'Java'],
    'Price': [400, 500, None, 350, 400, None],
    'Rating': [4, 5, 3, None, 4, 5],
    'Category': ['Programming', 'Programming', None, 'Database', 'Programming', 'Programming'],
    'Publisher': ['ABC', 'XYZ', 'ABC', None, 'ABC', 'XYZ']
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the dataset
print(df)

            Book  Price  Rating     Category Publisher
0         Python  400.0     4.0  Programming       ABC
1           Java  500.0     5.0  Programming       XYZ
2  C Programming    NaN     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC
5           Java    NaN     5.0  Programming       XYZ

In [35]:
# Check missing values in the Price column
print(df['Price'].isnull().sum())

2

In [36]:
# Replace missing Publisher values with Unknown
df['Publisher'] = df['Publisher'].fillna('Unknown')

# Display the updated Publisher column
print(df['Publisher'])

0        ABC
1        XYZ
2        ABC
3    Unknown
4        ABC
5        XYZ
Name: Publisher, dtype: str

In [37]:

# Remove rows that contain missing values
df_clean = df.dropna()

# Display the cleaned dataset
print(df_clean)

     Book  Price  Rating     Category Publisher
0  Python  400.0     4.0  Programming       ABC
1    Java  500.0     5.0  Programming       XYZ
4  Python  400.0     4.0  Programming       ABC

In [38]:
# Remove columns that contain at least one missing value
df_no_missing_columns = df.dropna(axis=1)

# Display the result
print(df_no_missing_columns)

            Book Publisher
0         Python       ABC
1           Java       XYZ
2  C Programming       ABC
3            SQL   Unknown
4         Python       ABC
5           Java       XYZ